[package]
name = "melior-asm"
version = "0.1.0"
edition = "2021"

[dependencies]
mlir-asm-proc = { path = "../melior-asm-proc" }

[dev-dependencies.melior-next]
git = "https://github.com/edg-l/melior-next"
